<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Driver_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * get a drivers record counts
     */
    function record_count()
    {
        return $this->db->count_all("tbl_drivers");
    }

    /*
     * List all drivers by limit
     */
    function list_all_drivers($limit,$per_page)
    {
        $this->db->select('tbl_drivers.*,tbl_car_type.car_type');
        $this->db->from('tbl_drivers');
        $this->db->join('tbl_car_type','tbl_car_type.id = tbl_drivers.car_type','left');
        $this->db->order_by("tbl_drivers.id", "desc"); 
        $this->db->limit($per_page,$limit);
        $query = $this->db->get();      
        $driver_data = array();
        if($query->num_rows() > 0)
        {
            $driver_data = $query->result_array();  
            
            foreach ($driver_data as $key => $value) {
                $ct = $this->db->get_where('tbl_documents',array('driver_id'=>$value['id']))->num_rows();
                if($ct > 0){
                    $driver_data[$key]['documents_submitted'] = '1';
                }
                else{
                    $driver_data[$key]['documents_submitted'] = '0';
                }
                $ct = $this->db->get_where('tbl_temp_documents',array('driver_id'=>$value['id']))->num_rows();
                if($ct > 0){
                    $driver_data[$key]['new_documents_submitted'] = '1';
                }
                else{
                    $driver_data[$key]['new_documents_submitted'] = '0';
                }
            }

            return $driver_data;
        }
        else
        {
            return false;
        }
    }

    /*
     * function to count searched drivers by value
     */
    function record_count_search($data)
    {   
        $query = $this->db->query("SELECT * FROM tbl_drivers WHERE fname LIKE '%".$data."%' OR lname LIKE '%".$data."%' OR email LIKE '%".$data."%' OR phone LIKE '%".$data."%' OR last_login LIKE '%".$data."%' ORDER BY id desc ");

        if($query->num_rows() > 0)
        {
            return $query->num_rows();
        }
        else
        {
            return false;
        }
    }

    /*
     * function to list searched value by drivers
     */
    function drivers_list_search($limit,$per_page,$data)
    {
        $this->db->select('tbl_drivers.*,tbl_car_type.car_type');
        $this->db->from('tbl_drivers');
        $this->db->where("fname LIKE '%".$data."%' OR lname LIKE '%".$data."%' OR email LIKE '%".$data."%' OR phone LIKE '%".$data."%' OR last_login LIKE '%".$data."%'");
        $this->db->join('tbl_car_type','tbl_car_type.id = tbl_drivers.car_type','left');
        $this->db->order_by("tbl_drivers.id", "desc"); 
        $this->db->limit($per_page,$limit);
        $query = $this->db->get();
        if($query->num_rows() > 0)
        {
            $driver_data = $query->result_array();
            foreach ($driver_data as $key => $value) {
                $ct = $this->db->get_where('tbl_documents',array('driver_id'=>$value['id']))->num_rows();
                if($ct > 0){
                    $driver_data[$key]['documents_submitted'] = '1';
                }
                else{
                    $driver_data[$key]['documents_submitted'] = '0';
                }
                $ct = $this->db->get_where('tbl_temp_documents',array('driver_id'=>$value['id']))->num_rows();
                if($ct > 0){
                    $driver_data[$key]['new_documents_submitted'] = '1';
                }
                else{
                    $driver_data[$key]['new_documents_submitted'] = '0';
                }
            }
            return $driver_data;
        }
        else
        {
            return false;
        }
    }

    /*
     * Get driver by id
     */
    function get_driver($id)
    {
        return $this->db->get_where('tbl_drivers',array('id'=>$id))->row_array();
    }

    /*
     * Get driver by id
     */
    function get_driverdocument($driver_id)
    {
        return $this->db->get_where('tbl_documents',array('driver_id'=>$driver_id))->row_array();
    }

    function get_new_driverdocument($driver_id)
    {
        return $this->db->get_where('tbl_temp_documents',array('driver_id'=>$driver_id))->row_array();
    }
    
    /*
     * Get all tbl_driver
     */
    function get_all_driver()
    {
        return $this->db->get('tbl_drivers')->result_array();
    }
    
    /*
     * function to add new tbl_driver
     */
    function add_driver($params)
    {
        $this->db->insert('tbl_drivers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_driver
     */
    function update_driver($id,$params)
    {
        $this->db->where('id',$id);
        $this->db->update('tbl_drivers',$params);
    }

    /*
     * function to update driver documents
     */
    function update_driverdocument($driver_id,$params)
    {
        $this->db->where('driver_id',$driver_id);
        $this->db->update('tbl_documents',$params);
    }
    
    /*
     * function to delete tbl_driver
     */
    function delete_driver($id)
    {
        $this->db->delete('tbl_drivers',array('id'=>$id));
    }
}
